spring:
  application:
    name: aztrainning

  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            - endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
            - credential:
                managed-identity-enabled: true

server:
  port: 80