spring:
  application:
    name: aztrainning

  cloud:
    azure:
      credentials:
        managed-identity-enabled: true
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT}

server:
  port: 80