spring:
  application:
    name: aztrainning
  h2:
    console:
      enabled: true #for testing purposes only
  liquibase:
    enabled: true

  cloud:
    azure:
      credentials:
        managed-identity-enabled: true
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
  datasource:
    url: h2:mem:practiceDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 80